//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Common.Configuration {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Common.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Application Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddApplicationSettingsTitle {
            get {
                return ResourceManager.GetString("AddApplicationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Configuration Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddConfigurationSourcesTitle {
            get {
                return ResourceManager.GetString("AddConfigurationSourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Instrumentation Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddInstrumentationSettingsTitle {
            get {
                return ResourceManager.GetString("AddInstrumentationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Settings 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppSettingsSectionMetadataDescription {
            get {
                return ResourceManager.GetString("AppSettingsSectionMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppSettingsSectionMetadataDisplayName {
            get {
                return ResourceManager.GetString("AppSettingsSectionMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The position of the handler within the policy handler chain, starting from 1. 
        ///The default value is zero, which means that there is no explicit order specified for 
        ///the handler in relation to other handlers in the same handler chain.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CallHandlerDataOrderDescription {
            get {
                return ResourceManager.GetString("CallHandlerDataOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CallHandlerDataOrderDisplayName {
            get {
                return ResourceManager.GetString("CallHandlerDataOrderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Localization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CategoryLocalization {
            get {
                return ResourceManager.GetString("CategoryLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (name)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A manageability provider for a configuration element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration Element Manageability Provider과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Configuration Element Manageability Provider.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type that is managed by the manageability provider.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTargetTypeDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTargetTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTargetTypeDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTargetTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Configuration Element Manageability Provider.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A manageability provider for a configuration section.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration Section Manageability Provider과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of Manageability Providers that the receiver might require to provide 
        ///manageability to configuration elements.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataManageabilityProvidersDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataManageabilityProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manageability Providers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataManageabilityProvidersDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataManageabilityProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Manageability Provider.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Manageability Provider.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The element that represents a configuration source .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An element that contains configurtain information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Configuration Source Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Configuration Source Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration settings that determine the sources of configuration information for an application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration Sources과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Configuration Source containing the section that this Redirected Section will override.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionParentSourceDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionParentSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionParentSourceDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionParentSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The list of Redirected Sections for this application configuration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionRedirectedSectionsDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionRedirectedSectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirected Sections과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionRedirectedSectionsDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionRedirectedSectionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the default Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionSelectedSourceDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSelectedSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionSelectedSourceDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSelectedSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The collection of defined configuration sources.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionSourcesDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sources과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationSourceSectionSourcesDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSourcesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A custom implementation of a Call Handler that is added to Enterprise Library.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomCallHandlerDataDescription {
            get {
                return ResourceManager.GetString("CustomCallHandlerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Call Handler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomCallHandlerDataDisplayName {
            get {
                return ResourceManager.GetString("CustomCallHandlerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Custom Call Handler.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomCallHandlerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CustomCallHandlerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomCallHandlerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CustomCallHandlerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Configuration Source that reads configuration information from a disk file. 
        ///The file must contain XML data in the standard .NET configuration format.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File-based Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path and name of the configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration files (*.config)|*.config|All Files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathFilter {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the File-based Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the File-based Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unique name for the Application Instance to be used by the Instrumentation providers.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionApplicationInstanceNameDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionApplicationInstanceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Instance Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionApplicationInstanceNameDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionApplicationInstanceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration settings for Instrumentation for the entire application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instrumentation Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies if logging to Windows Event Log will take place when instrumented 
        ///events occur within Enterprise Library.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionEventLoggingEnabledDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionEventLoggingEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Logging Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionEventLoggingEnabledDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionEventLoggingEnabledDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies if the Enterprise Library Performance Counters will be exposed and updated 
        ///when instrumented events occur within Enterprise Library.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionPerformanceCountersEnabledDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionPerformanceCountersEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance Counters Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationConfigurationSectionPerformanceCountersEnabledDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionPerformanceCountersEnabledDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationCollectionMetadataDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationCollectionMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationCollectionMetadataDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationCollectionMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A custom application settings, such as file paths or XML Web service URLs.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataKeyDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataKeyDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataValueDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataValueDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataValueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the application. 
        ///This used to determine the Registry path for the configuration information. 
        ///This value is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementApplicationNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementApplicationNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementApplicationNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementApplicationNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The collection of registered types necessary to provide manageability by the configuration source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementConfigurationManageabilityProvidersDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementConfigurationManageabilityProvidersDescriptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration Manageability Providers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementConfigurationManageabilityProvidersDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementConfigurationManageabilityProvidersDisplayNam" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A configuration source that integrates with Group Policy to apply domain-wide or 
        ///local machine policy overrides to provide centralized configuration management capabilities.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manageable Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies if the configuration source will take account of domain-wide or 
        ///local machine policy overrides configured in the Registry through Group Policy settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementEnableGroupPoliciesDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementEnableGroupPoliciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group Policy Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementEnableGroupPoliciesDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementEnableGroupPoliciesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path and name of the configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementFilePathDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementFilePathDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementFilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Manageable Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Manageable Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A configuration element in a collection that is keyed by the name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedConfigurationElementDescription {
            get {
                return ResourceManager.GetString("NamedConfigurationElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Named Configuration Element과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedConfigurationElementDisplayName {
            get {
                return ResourceManager.GetString("NamedConfigurationElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name used to identify this item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedConfigurationElementNameDescription {
            get {
                return ResourceManager.GetString("NamedConfigurationElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedConfigurationElementNameDisplayName {
            get {
                return ResourceManager.GetString("NamedConfigurationElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of Named Configuration elements.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedElementCollectionDescription {
            get {
                return ResourceManager.GetString("NamedElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Named Element Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamedElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("NamedElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of Name Type Configuration elements.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementCollectionDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name Type Configuration Element Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A configuration element in a collection that contains both a type and a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name Type Configuration Element과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Name Type Configuration Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementNameDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementNameDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the Name Type Configuration Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementTypeNameDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTypeConfigurationElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A base class from which all implementations of polymorphic configuration collections derive.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PolymorphicConfigurationElementCollectionDescription {
            get {
                return ResourceManager.GetString("PolymorphicConfigurationElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polymorphic Configuration Element Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PolymorphicConfigurationElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("PolymorphicConfigurationElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A redirected section for the application configuration. 
        ///Each section of the configuration can be loaded from a different configuration source if required. 
        ///Each Redirected Section configured in this list will override the same entire section in 
        ///the default Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirected Section과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Redirected Section.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementNameDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementNameDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Configuration Source that will handle the redirected section. 
        ///Must be one of the Configuration Sources defined for the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementSourceNameDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementSourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RedirectedSectionElementSourceNameDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementSourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents a configuration section that can be serialized and deserialized to XML.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SerializableConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("SerializableConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serializable Configuration Section과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SerializableConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("SerializableConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A configuration source that reads configuration data from the default configuration file. 
        ///Typically this is App.config or Web.config, depending on the application type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the System Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The fully qualified type name of the System Configuration Source.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SystemConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of Type Registration Provider elements.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementCollectionDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Registration Provider Element Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A provider for registering types.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Registration Provider Element과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the Type Registration Provider Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the type that implements the Type Registration Provider Element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementProviderTypeNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementProviderTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider Type Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementProviderTypeNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementProviderTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the configuration section within the configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementSectionNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementSectionNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProviderElementSectionNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementSectionNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The section of the configuration that specifies the Type Registration Providers for the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Registration Providers Configuration Section과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of Type Registration providers.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDescription" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Registration Providers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDisplayName" +
                        "", resourceCulture);
            }
        }
    }
}
