//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.Properti" +
                            "es.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Expected an instance of InstrumentationConfigurationSection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementNotInstrumentationConfigurationSection {
            get {
                return ResourceManager.GetString("ConfigurationElementNotInstrumentationConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected and instance of &apos;{0}&apos; but got an instance of &apos;{1}&apos; instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationElementOfWrongType {
            get {
                return ResourceManager.GetString("ConfigurationElementOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attributes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomProviderAttributesPartName {
            get {
                return ResourceManager.GetString("CustomProviderAttributesPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomProviderTypePartName {
            get {
                return ResourceManager.GetString("CustomProviderTypePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A started category is required to perform the operation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmBuildingNoCurrentCategory {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingNoCurrentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A started policy is required to perform the operation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmBuildingNoCurrentPolicy {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingNoCurrentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A policy construction is in process.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmBuildingPolicyNotFinished {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingPolicyNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The built content is requested but there are outstanding categories being built.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmBuildingProcessNotFinished {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingProcessNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default value is above the max value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} versus {3}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmDefaultValueAboveMaxValue {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueAboveMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default value is below the min value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} versus {3}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmDefaultValueBelowMinValue {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueBelowMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default value for part &apos;{0}&apos; on policy &apos;{1}&apos; is longer than the max length {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmDefaultValueLongerThanMaxlen {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueLongerThanMaxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registry key path contains invalid characters or is missing parts: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmInvalidCharactersInRegistryKey {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidCharactersInRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The default value is invalid: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmInvalidDefaultValue {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The max len of {2} is invalid on part &apos;{0}&apos; for policy &apos;{1}&apos;. The allowed values are 0-1024.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmInvalidMaxlen {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidMaxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String &apos;{0}&apos; is not a valid name on an ADM template.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmInvalidName {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The suggestion is invalid: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmInvalidSuggestion {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min value is larger than max value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} versus {3}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmMinValueLargerThanMaxValue {
            get {
                return ResourceManager.GetString("ExceptionAdmMinValueLargerThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The numeric constraint &apos;{2}&apos; for part &apos;{0}&apos; on policy &apos;{1}&apos; is outside the allowed range. The valued values are 0-999999999. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmNumericConstraintOutsideRange {
            get {
                return ResourceManager.GetString("ExceptionAdmNumericConstraintOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path segment over 255 chars in length for registry key: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmRegistryKeyPathSegmentTooLong {
            get {
                return ResourceManager.GetString("ExceptionAdmRegistryKeyPathSegmentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registry value name over 255 chars in length: &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionAdmRegistryValueNameTooLong {
            get {
                return ResourceManager.GetString("ExceptionAdmRegistryValueNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application name cannot be longer than 255 characters.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionApplicationNameTooLong {
            get {
                return ResourceManager.GetString("ExceptionApplicationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter is an empty string과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionArgumentEmpty {
            get {
                return ResourceManager.GetString("ExceptionArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group policy processing could not be locked prior to reading the registry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionCannotLockGroupPolicy {
            get {
                return ResourceManager.GetString("ExceptionCannotLockGroupPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration file {0} could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception caught from callback for change on section &apos;{0}&apos; calling method &apos;{1}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionErrorOnCallbackForSectionUpdate {
            get {
                return ResourceManager.GetString("ExceptionErrorOnCallbackForSectionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error was detected while a configuration element&apos;s properties were being overriden with policy values.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionErrorWhileOverriding {
            get {
                return ResourceManager.GetString("ExceptionErrorWhileOverriding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no value with name &apos;{1}&apos; on key &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionMissingRegistryValue {
            get {
                return ResourceManager.GetString("ExceptionMissingRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value for &apos;{1}&apos; on key &apos;{0}&apos; is not a valid value name for enum type &apos;{2}&apos;: &apos;{3}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionRegistryValueNotEnumValue {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueNotEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value for &apos;{1}&apos; on key &apos;{0}&apos; is not a valid assembly qualified type name: &apos;{2}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionRegistryValueNotTypeName {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueNotTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value for &apos;{1}&apos; on key &apos;{0}&apos; is not of the correct type:
        ///Expected {2} but got {3} instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionRegistryValueOfWrongType {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value can not be null or string or empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error while processing section &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionUnexpectedErrorProcessingSection {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedErrorProcessingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The expected type &apos;{0}&apos; was not provided.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionUnexpectedType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group policy notification thread과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupPolicyWatcherThread {
            get {
                return ResourceManager.GetString("GroupPolicyWatcherThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instrumentation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationSectionCategoryName {
            get {
                return ResourceManager.GetString("InstrumentationSectionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event logging enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationSectionEventLoggingEnabledPartName {
            get {
                return ResourceManager.GetString("InstrumentationSectionEventLoggingEnabledPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance counters enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationSectionPerformanceCountersEnabledPartName {
            get {
                return ResourceManager.GetString("InstrumentationSectionPerformanceCountersEnabledPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify settings for the instrumentation section과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InstrumentationSectionPolicyName {
            get {
                return ResourceManager.GetString("InstrumentationSectionPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manageable Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updates to configuration through the ManageableConfigurationSource are not supported. Use the FileConfigurationSource instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageableConfigurationSourceUpdateNotAvailable {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceUpdateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoneListItem {
            get {
                return ResourceManager.GetString("NoneListItem", resourceCulture);
            }
        }
    }
}
