//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot create design source for rootSource other than DesignConfigurationSource.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CannotCreateDesignSource {
            get {
                return ResourceManager.GetString("CannotCreateDesignSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type &apos;{0}&apos; defined in the &apos;{1}&apos; configuration source is invalid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfigurationSourceInvalidTypeErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationSourceInvalidTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The exception that occured was: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventLogEntryExceptionTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred in application {0} in the {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventLogEntryHeaderTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type &apos;{0}&apos; does not derive from IDictionary.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionArgumentShouldDeriveFromIDictionary {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type &apos;{0}&apos; does not derive from IList.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionArgumentShouldDeriveFromIList {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The [Assembler] attribute is not set in the configuration object type {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionAssemblerAttributeNotSet {
            get {
                return ResourceManager.GetString("ExceptionAssemblerAttributeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The assembler configured for type {0} has type {2} which is not compatible with type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionAssemblerTypeNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionAssemblerTypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The base ConfigurationSourceElement configuration type can not be used as a concrete configuration element.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionBaseConfigurationSourceElementIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionBaseConfigurationSourceElementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add new paramters after Finish() or Dispose().과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionCannotAddParametersAfterDispose {
            get {
                return ResourceManager.GetString("ExceptionCannotAddParametersAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The AssemblyQualifiedTypeNameConverter can only convert values of type &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionCanNotConvertType {
            get {
                return ResourceManager.GetString("ExceptionCanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Builder has already added policies.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionCannotFinish {
            get {
                return ResourceManager.GetString("ExceptionCannotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The section {0} could not be saved because the file does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration file {0} could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration object for type &apos;{0}&apos; with name &apos;{1}&apos; has type &apos;{2}&apos; which is does not implement ICustomProviderData.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationObjectIsNotCustomProviderData {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectIsNotCustomProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The concrete type for polymorphic object named &apos;{1}&apos; in hierarchy {2} is not defined in configuration object {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration section &apos;{0}&apos; specifies Source &apos;{1}&apos;, which is not declared in the configuration sources section.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationSectionPointsToNonExistingSource {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSectionPointsToNonExistingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A configuration source named &apos;{0}&apos; was not found in the {1} section.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationSourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration source section is not found in the application configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionConfigurationSourceSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSourceSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The required &quot;ContainerPolicyCreatorAttribute&quot; is not present in the supplied type &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionContainerPolicyCreatorAttributeNotPresent {
            get {
                return ResourceManager.GetString("ExceptionContainerPolicyCreatorAttributeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The [CustomFactory] attribute was not found on type {0} while processing request for id &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionCustomFactoryAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionCustomFactoryAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0}&apos; specified as a custom provider does not have the required public constructor with a single NameValueCollection parameter.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionCustomProviderTypeDoesNotHaveTheRequiredConstructor {
            get {
                return ResourceManager.GetString("ExceptionCustomProviderTypeDoesNotHaveTheRequiredConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was an error raising an event in 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionEventRaisingFailed {
            get {
                return ResourceManager.GetString("ExceptionEventRaisingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The method with signature {0} is not a valid factory method to build type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionFactoryMethodHasInvalidReturnType {
            get {
                return ResourceManager.GetString("ExceptionFactoryMethodHasInvalidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot merge the configuration element.
        ///The local elements type &apos;{0}&apos; is  incompatible with the parent elements type &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionIncompaitbleMergeElementType {
            get {
                return ResourceManager.GetString("ExceptionIncompaitbleMergeElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type &apos;{0}&apos; cannot be resolved. Please verify the spelling is correct or that the full type name is provided.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionInvalidType {
            get {
                return ResourceManager.GetString("ExceptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The supplied configuration object has type &apos;{0}&apos;, which is not a descendant of &apos;NameTypeConfigurationElement&apos; as required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionMustBeNameTypeConfigurationElement {
            get {
                return ResourceManager.GetString("ExceptionMustBeNameTypeConfigurationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The required zero argument constructor is not available for the supplied type &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionMustHaveNoArgsConstructor {
            get {
                return ResourceManager.GetString("ExceptionMustHaveNoArgsConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The required interface &quot;IContainerPolicyCreator&quot; is not implemented by the supplied type &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionMustImplementIContainerPolicyCreator {
            get {
                return ResourceManager.GetString("ExceptionMustImplementIContainerPolicyCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration could not be found for name &apos;{0}&apos; in factory {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNamedConfigurationNotFound {
            get {
                return ResourceManager.GetString("ExceptionNamedConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} does not contain the ConfigurationElementTypeAttribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoConfigurationElementAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No policy specifying the configuration source for the container has been set. The EnterpriseLibraryCoreExtension is probably missing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoConfigurationObjectPolicySet {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationObjectPolicySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No public constructor with {1} arguments was found for type &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoMatchingConstructorFound {
            get {
                return ResourceManager.GetString("ExceptionNoMatchingConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} does not have a public method annotated as an injection target as required by the use of injection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoMethodAnnotatedForInjectionFound {
            get {
                return ResourceManager.GetString("ExceptionNoMethodAnnotatedForInjectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} does not have a static method with a TargetConstructorAttribuite suitable to create an object of type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoSuitableFactoryMethodFound {
            get {
                return ResourceManager.GetString("ExceptionNoSuitableFactoryMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type attribute does not exist on the element {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionNoTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter &apos;{0}&apos; for injection target &apos;{1}&apos; in type &apos;{2}&apos; is missing the injection interpretation attribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionParameterNotAnnotatedForInjection {
            get {
                return ResourceManager.GetString("ExceptionParameterNotAnnotatedForInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The performance counter &apos;{0}&apos; in category &apos;{1}&apos; is redefined in type {2} with a different configuration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionPerformanceCounterRedefined {
            get {
                return ResourceManager.GetString("ExceptionPerformanceCounterRedefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attempt to continue working with a PolicyBuilder after the policies have been added to a policy list for type &apos;{1}&apos; with key &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionPolicyBuilderFinished {
            get {
                return ResourceManager.GetString("ExceptionPolicyBuilderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified policies cannot be added: a property policy mapping is still taking place.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionPolicyBuilderStillWaitingForPropertyPolicy {
            get {
                return ResourceManager.GetString("ExceptionPolicyBuilderStillWaitingForPropertyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The supplied expression is not a valid property access expression: &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionPropertyAccessExpressionNotPropertyAccess {
            get {
                return ResourceManager.GetString("ExceptionPropertyAccessExpressionNotPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   e {2}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionPropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to find the redirected section {0} in the specified configuration source {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionRedirectedConfigurationSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionRedirectedConfigurationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service type of {0} is not compatible with supplied expression type of {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionRegistrationServiceTypeIsNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionRegistrationServiceTypeIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lambda expression must construct a new instance of a type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionRegistrationTypeExpressionMustBeNewLambda {
            get {
                return ResourceManager.GetString("ExceptionRegistrationTypeExpressionMustBeNewLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} does not contain the ConfigurationDataRetrievalAttribute required to resolve named references.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionRetrievalAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionRetrievalAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method must be overriden by subclass.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionShouldBeImplementedBySubclass {
            get {
                return ResourceManager.GetString("ExceptionShouldBeImplementedBySubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve parameter value. The property {0} does not exist for type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionSourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionSourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value can not be null or string or empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A creation expression must be a constructor call, but the supplied expression was &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionSuppliedCreationExpressionIsNotNewExpression {
            get {
                return ResourceManager.GetString("ExceptionSuppliedCreationExpressionIsNotNewExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system configuration source is not defined in the configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionSystemSourceNotDefined {
            get {
                return ResourceManager.GetString("ExceptionSystemSourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The configuration object for default provider named &apos;{0}&apos; for type &apos;{1}&apos; was not found in the supplied list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTheSpecifiedDefaultProviderDoesNotExistInConfiguration {
            get {
                return ResourceManager.GetString("ExceptionTheSpecifiedDefaultProviderDoesNotExistInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} from configuration could not be created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeCouldNotBeCreated {
            get {
                return ResourceManager.GetString("ExceptionTypeCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type does not provide a constructor taking a single parameter type of NameValueCollection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeDoesNotProvideCorrectConstructor {
            get {
                return ResourceManager.GetString("ExceptionTypeDoesNotProvideCorrectConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type must be derived from &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeMustDeriveFromType {
            get {
                return ResourceManager.GetString("ExceptionTypeMustDeriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type must implement interface &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeMustImplementInterface {
            get {
                return ResourceManager.GetString("ExceptionTypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type {0} is not an implementation of ICustomFactory for CustomFactoryAttribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeNotCustomFactory {
            get {
                return ResourceManager.GetString("ExceptionTypeNotCustomFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type {0} is not an implementation of IConfigurationNameMapper for ConfigurationNameMapperAttribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeNotNameMapper {
            get {
                return ResourceManager.GetString("ExceptionTypeNotNameMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type {0} is not an implementation of IConfigurationDataRetriever for ConfigurationDataRetrievalAttribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionTypeNotRetriever {
            get {
                return ResourceManager.GetString("ExceptionTypeNotRetriever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default policy creation failed: The properties in the supplied configuration object of type {0} cannot be matched to any constructor on type {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnableToMatchConstructorToConfigurationObject {
            get {
                return ResourceManager.GetString("ExceptionUnableToMatchConstructorToConfigurationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The expected type &apos;{0}&apos; was not provided.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnexpectedType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An call to an unknown method named &apos;{0}&apos; in the Resolve class was found in the supplied argument expression: &apos;{1}&apos;. Cannot create policies for this expression.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnknownResolveMethod {
            get {
                return ResourceManager.GetString("ExceptionUnknownResolveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unrecognized Container marker method.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnrecognizedContainerMarkerMethod {
            get {
                return ResourceManager.GetString("ExceptionUnrecognizedContainerMarkerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unrecognized DependencyParameter type: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnrecognizedDependencyParameterType {
            get {
                return ResourceManager.GetString("ExceptionUnrecognizedDependencyParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The initialization expression for property {0} is not supported: only simple bindings are supported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExceptionUnsupportedBindingExpressionType {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedBindingExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileConfigurationSourceName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Configuration Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemConfigurationSourceName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceName", resourceCulture);
            }
        }
    }
}
